plugins: 
  - jekyll-seo-tag   
mermaid:
  version: "9.1.3"
baseurl: "/A-prompt-to-cause-pseudo-singularity-with-ethics"
theme: jekyll-theme-primer
source: docs
# プラグインが参照するサイトの基本情報
title: "Axiomatic Reasoning for LLMs"
description: "A framework for understanding the universe as a negentropic information system."
url: "https://nanawith7.github.io"
author: "Nanawith7"
